from ads_manager import enums
from ads_manager.integrations.clients.facebook import schemas as facebook_client_schemas

FACEBOOK_RESOURCE_DETAILS_FIELDS = {
    enums.ResourceType.CAMPAIGN: [
        "account_id",
        "id",
        "name",
        "effective_status",
        "configured_status",
        "created_time",
        "updated_time",
    ],
    enums.ResourceType.AD_SET: [
        "account_id",
        "campaign_id",
        "id",
        "name",
        "effective_status",
        "configured_status",
        "created_time",
        "updated_time",
    ],
    enums.ResourceType.AD: [
        "account_id",
        "campaign_id",
        "adset_id",
        "id",
        "name",
        "effective_status",
        "configured_status",
        "created_time",
        "updated_time",
    ],
    enums.ResourceType.AD_CREATIVE: [
        "id",
        "account_id",
        "name",
        "title",
        "body",
        "image_url",
    ],
}


FACEBOOK_INSIGHTS_DETAILS_FIELDS = {
    enums.ResourceType.CAMPAIGN: [
        "account_id",
        "account_name",
        "campaign_id",
        "campaign_name",
        "spend",
        "impressions",
        "clicks",
        "ctr",
        "cpm",
        "cpc",
        "reach",
        "actions",
        "conversions",
        "cost_per_conversion",
        "date_start",
        "date_stop",
    ],
    enums.ResourceType.AD_SET: [
        "account_id",
        "account_name",
        "campaign_id",
        "campaign_name",
        "adset_id",
        "adset_name",
        "spend",
        "impressions",
        "clicks",
        "ctr",
        "cpm",
        "cpc",
        "reach",
        "actions",
        "conversions",
        "cost_per_conversion",
        "date_start",
        "date_stop",
    ],
    enums.ResourceType.AD: [
        "account_id",
        "account_name",
        "campaign_id",
        "campaign_name",
        "adset_id",
        "adset_name",
        "ad_id",
        "ad_name",
        "spend",
        "impressions",
        "clicks",
        "ctr",
        "cpm",
        "cpc",
        "reach",
        "actions",
        "conversions",
        "cost_per_conversion",
        "date_start",
        "date_stop",
    ],
}


FACEBOOK_INSIGHTS_SCHEMAS = {
    enums.ResourceType.CAMPAIGN: facebook_client_schemas.CampaignsInsightReport,
    enums.ResourceType.AD_SET: facebook_client_schemas.AdSetsInsightReport,
    enums.ResourceType.AD: facebook_client_schemas.AdsInsightReport,
}
